apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-manager-master
  namespace: wazuh
spec:
  storageClassName: gce-pd-encrypted-retained
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  # volumeMode: Filesystem
  # persistentVolumeReclaimPolicy: Recycle
#  mountOptions:
#    - hard
#    - nfsvers=4.1
  hostPath:
    path: "/var/wazuh-manager-master"
#    server: 172.17.0.2