apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-elasticsearch
  namespace: wazuh
spec:
  storageClassName: gce-pd-encrypted-retained
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  # volumeMode: Filesystem
  # persistentVolumeReclaimPolicy: Recycle
#  mountOptions:
#    - hard
#    - nfsvers=4.1
  hostPath:
    path: "/"
#    server: 172.17.0.2